language: java
jdk:
- oraclejdk8
os:
- linux
script:
- "./gradlew clean build"
deploy:
  provider: script
  script: "./travis-release-script"
  on:
    branch: master
env:
  global:
    secure: BjWIEGFZPJ04jMms6xdiQBGfTzp5e48BhqgFUhucDd2VbHoR2TfjgqY3N2aQW10ygpZDIv7rF957kSH5OKbCG2268EJk6UWQcS9lf7YpsmAR/ft0WxIdPVah0UXV+S9onVQYMg7BVtad/t/F0L7HKLlxx/0HC8iTq2aAxMsTm2uD1e2Os6OCfXknlNg6p0KFS8AJ8/FvyhcgTJlhPefN6UDW1yXjjzoWqr7DkoFh8naIy860Yt3n/w5ByTPqVRDgHtihuJynFxItIgCgDnkMmOIqsoqbY9YbBERSK8XPW8ZfiDRhaLhtGvSgac71paayu9FhaJgMif2ljx4a4pYdjoY4wXvbpv1jKv30lgdJd+ot0XHXE4pEwEHRGXB/fwPbprrblsZ39BUVG26f2mLPylVFdwAAmdPj5X9J4tf5HQpz8tMVqD6tmPQpxpzedRjXlieZqpUb6R6i9ZOw2CbDxAEPSh3OnLpHP07Ip6RrlZmCY05pwcWGlP0R5OJl87d0B/HEjfuFAqYSxS9pmbGEtiJZzaY0vVHoebY5aanCKJ0lXqe2uoJFruwZB1z6DN3jTz4hLdYdmrWDXtXDS5DfCNDJ6tkkgVTOM0bvm13NYgKoDsriwhc9uC2Y5fLAGXcJhT7NRYem4ljAYKMrwJhdWGgL9EOAXoXextnXdgWRaP4=
