language: java
jdk:
- oraclejdk8
os:
- linux
script:
- ./gradlew clean build
deploy:
  provider: script
  script: git checkout $TRAVIS_BRANCH && ./gradlew release -Prelease.useAutomaticVersion=true
  on:
    branch: master