#!/usr/bin/env bash
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git checkout $TRAVIS_BRANCH

git remote set-url --push origin https://${GH_TOKEN}@github.com/poeatlas/cli.git

./gradlew release -Prelease.useAutomaticVersion=true